// 🗑️ Comprehensive Lagos State Smart Bin Network - 1000+ Locations

const bins = [
  // LAGOS ISLAND DISTRICT (Dense Commercial & Financial Hub) - Ward D
  {
    id: "bin001",
    name: "Marina - Nigerian Stock Exchange",
    fill: 85,
    position: [6.4541, 3.3947],
    status: "critical",
    lastCollection: new Date("2025-01-19"),
    ward: "Ward D",
    wasteBreakdown: [
      { type: "Paper", weight: 3.4 },
      { type: "Plastic", weight: 2.1 },
      { type: "Mixed", weight: 1.7 },
      { type: "Glass", weight: 0.8 },
      { type: "Organic", weight: 0.5 },
    ],
  },
  {
    id: "bin002",
    name: "Marina - Central Bank of Nigeria",
    fill: 78,
    position: [6.4535, 3.3955],
    status: "high",
    lastCollection: new Date("2025-02-18"),
    ward: "Ward D",
    wasteBreakdown: [
      { type: "Paper", weight: 3.1 },
      { type: "Plastic", weight: 1.9 },
      { type: "Mixed", weight: 1.6 },
      { type: "Organic", weight: 0.8 },
      { type: "Glass", weight: 0.4 },
    ],
  },
  {
    id: "bin003",
    name: "Marina - Federal Secretariat",
    fill: 72,
    position: [6.4548, 3.3962],
    status: "moderate",
    lastCollection: new Date("2025-03-19"),
    ward: "Ward D",
    wasteBreakdown: [
      { type: "Paper", weight: 2.9 },
      { type: "Plastic", weight: 1.8 },
      { type: "Mixed", weight: 1.4 },
      { type: "Organic", weight: 0.7 },
      { type: "E-waste", weight: 0.4 },
    ],
  },
  {
    id: "bin004",
    name: "Balogun Market - Main Entrance",
    fill: 92,
    position: [6.4512, 3.3856],
    status: "critical",
    lastCollection: new Date("2025-01-15"),
    ward: "Ward D",
    wasteBreakdown: [
      { type: "Organic", weight: 5.7 },
      { type: "Plastic", weight: 4.3 },
      { type: "Mixed", weight: 2.8 },
      { type: "Paper", weight: 1.1 },
      { type: "Glass", weight: 0.3 },
    ],
  },
  {
    id: "bin005",
    name: "Balogun Market - Electronics Section",
    fill: 88,
    position: [6.4508, 3.3862],
    status: "critical",
    lastCollection: new Date("2025-01-25"),
    ward: "Ward D",
    wasteBreakdown: [
      { type: "E-waste", weight: 5.8 },
      { type: "Plastic", weight: 3.2 },
      { type: "Mixed", weight: 2.4 },
      { type: "Paper", weight: 1.9 },
      { type: "Glass", weight: 0.5 },
    ],
  },
  {
    id: "bin006",
    name: "Balogun Market - Textile Section",
    fill: 84,
    position: [6.4516, 3.385],
    status: "critical",
    lastCollection: new Date("2025-02-16"),
    ward: "Ward D",
    wasteBreakdown: [
      { type: "Mixed", weight: 4.6 },
      { type: "Plastic", weight: 3.4 },
      { type: "Organic", weight: 2.1 },
      { type: "Paper", weight: 1.3 },
    ],
  },
  {
    id: "bin007",
    name: "CMS Bus Terminal - Main Gate",
    fill: 90,
    position: [6.4598, 3.3853],
    status: "critical",
    lastCollection: new Date("2025-01-28"),
    ward: "Ward D",
    wasteBreakdown: [
      { type: "Organic", weight: 4.1 },
      { type: "Plastic", weight: 3.8 },
      { type: "Mixed", weight: 3.2 },
      { type: "Paper", weight: 1.6 },
      { type: "Glass", weight: 0.8 },
    ],
  },
  {
    id: "bin008",
    name: "CMS - Race Course",
    fill: 76,
    position: [6.4605, 3.386],
    status: "high",
    lastCollection: new Date("2025-04-17"),
    ward: "Ward D",
    wasteBreakdown: [
      { type: "Mixed", weight: 2.4 },
      { type: "Plastic", weight: 2.0 },
      { type: "Organic", weight: 1.6 },
      { type: "Paper", weight: 1.2 },
      { type: "Glass", weight: 0.9 },
    ],
  },
  {
    id: "bin009",
    name: "Broad Street - Banking District",
    fill: 82,
    position: [6.4567, 3.3889],
    status: "high",
    lastCollection: new Date("2025-03-12"),
    ward: "Ward D",
    wasteBreakdown: [
      { type: "Paper", weight: 3.9 },
      { type: "Plastic", weight: 2.5 },
      { type: "Mixed", weight: 2.0 },
      { type: "Organic", weight: 1.0 },
      { type: "Glass", weight: 0.4 },
    ],
  },
  {
    id: "bin010",
    name: "Broad Street - Commercial District",
    fill: 79,
    position: [6.4573, 3.3895],
    status: "high",
    lastCollection: new Date("2025-04-08"),
    ward: "Ward D",
    wasteBreakdown: [
      { type: "Paper", weight: 3.8 },
      { type: "Plastic", weight: 2.4 },
      { type: "Mixed", weight: 1.9 },
      { type: "Organic", weight: 1.1 },
      { type: "Glass", weight: 0.3 },
    ],
  },
  {
    id: "bin011",
    name: "Lagos Island - King George V Park",
    fill: 65,
    position: [6.4525, 3.3875],
    status: "moderate",
    lastCollection: new Date("2025-05-18"),
    ward: "Ward D",
    wasteBreakdown: [
      { type: "Organic", weight: 2.8 },
      { type: "Plastic", weight: 1.7 },
      { type: "Mixed", weight: 1.2 },
      { type: "Paper", weight: 1.0 },
      { type: "Glass", weight: 0.2 },
    ],
  },
  {
    id: "bin012",
    name: "Lagos Island - Catholic Mission Street",
    fill: 71,
    position: [6.458, 3.384],
    status: "moderate",
    lastCollection: new Date("2025-04-28"),
    ward: "Ward D",
    wasteBreakdown: [
      { type: "Mixed", weight: 2.4 },
      { type: "Plastic", weight: 2.0 },
      { type: "Organic", weight: 1.6 },
      { type: "Paper", weight: 1.2 },
      { type: "Glass", weight: 0.9 },
    ],
  },

  // VICTORIA ISLAND (Commercial & Business Hub) - Ward D
  {
    id: "bin021",
    name: "Victoria Island - Adeola Odeku Street",
    fill: 68,
    position: [6.4269, 3.4314],
    status: "moderate",
    lastCollection: new Date("2025-05-18"),
    ward: "Ward D",
    wasteBreakdown: [
      { type: "Paper", weight: 3.2 },
      { type: "Plastic", weight: 2.0 },
      { type: "Mixed", weight: 1.6 },
      { type: "Organic", weight: 0.8 },
      { type: "Glass", weight: 0.5 },
    ],
  },
  {
    id: "bin022",
    name: "Victoria Island - Ahmadu Bello Way",
    fill: 45,
    position: [6.4281, 3.4219],
    status: "low",
    lastCollection: new Date("2025-06-20"),
    ward: "Ward D",
    wasteBreakdown: [
      { type: "Plastic", weight: 1.2 },
      { type: "Mixed", weight: 1.1 },
      { type: "Paper", weight: 1.0 },
      { type: "Organic", weight: 0.9 },
      { type: "Glass", weight: 0.4 },
    ],
  },

  // IKEJA DIVISION (Capital Territory & Tech Hub) - Ward E
  {
    id: "bin073",
    name: "Ikeja - Computer Village Main Market",
    fill: 96,
    position: [6.6056, 3.3598],
    status: "critical",
    lastCollection: new Date("2025-01-14"),
    ward: "Ward E",
    wasteBreakdown: [
      { type: "E-waste", weight: 10.2 },
      { type: "Plastic", weight: 5.7 },
      { type: "Mixed", weight: 3.4 },
      { type: "Paper", weight: 2.8 },
      { type: "Glass", weight: 0.6 },
    ],
  },
  {
    id: "bin074",
    name: "Ikeja - Computer Village Electronics Plaza",
    fill: 94,
    position: [6.6062, 3.3605],
    status: "critical",
    lastCollection: new Date("2025-01-25"),
    ward: "Ward E",
    wasteBreakdown: [
      { type: "E-waste", weight: 9.6 },
      { type: "Plastic", weight: 5.3 },
      { type: "Mixed", weight: 3.2 },
      { type: "Paper", weight: 2.6 },
      { type: "Glass", weight: 0.6 },
    ],
  },

  // BADAGRY DIVISION - Ward A
  {
    id: "bin091",
    name: "Badagry - Seme Border Checkpoint",
    fill: 82,
    position: [6.4167, 2.8833],
    status: "high",
    lastCollection: new Date("2025-03-16"),
    ward: "Ward A",
    wasteBreakdown: [
      { type: "Mixed", weight: 3.3 },
      { type: "Plastic", weight: 2.7 },
      { type: "Organic", weight: 2.2 },
      { type: "Paper", weight: 1.6 },
      { type: "Glass", weight: 1.1 },
    ],
  },
  {
    id: "bin092",
    name: "Badagry - Central Market",
    fill: 89,
    position: [6.415, 2.885],
    status: "critical",
    lastCollection: new Date("2025-01-15"),
    ward: "Ward A",
    wasteBreakdown: [
      { type: "Organic", weight: 6.5 },
      { type: "Plastic", weight: 4.9 },
      { type: "Mixed", weight: 2.8 },
      { type: "Paper", weight: 1.5 },
      { type: "Glass", weight: 0.6 },
    ],
  },

  // IKORODU DIVISION - Ward B
  {
    id: "bin105",
    name: "Ikorodu - Central Market",
    fill: 87,
    position: [6.6156, 3.5106],
    status: "critical",
    lastCollection: new Date("2025-02-15"),
    ward: "Ward B",
    wasteBreakdown: [
      { type: "Organic", weight: 6.1 },
      { type: "Plastic", weight: 4.2 },
      { type: "Mixed", weight: 2.6 },
      { type: "Paper", weight: 1.7 },
      { type: "Glass", weight: 0.6 },
    ],
  },

  // EPE DIVISION - Ward B
  {
    id: "bin119",
    name: "Epe - Fish Market (Main)",
    fill: 94,
    position: [6.5789, 3.9789],
    status: "critical",
    lastCollection: new Date("2025-01-14"),
    ward: "Ward B",
    wasteBreakdown: [
      { type: "Organic", weight: 6.8 },
      { type: "Plastic", weight: 5.1 },
      { type: "Mixed", weight: 2.6 },
      { type: "Paper", weight: 1.8 },
      { type: "Glass", weight: 0.8 },
    ],
  },

  // MAINLAND AREAS - Ward C
  {
    id: "bin32",
    name: "Surulere - Adeniran Ogunsanya",
    fill: 41,
    position: [6.5056, 3.3606],
    status: "low",
    lastCollection: new Date("2025-06-19"),
    ward: "Ward C",
    wasteBreakdown: [
      { type: "Mixed", weight: 1.6 },
      { type: "Plastic", weight: 1.3 },
      { type: "Organic", weight: 1.0 },
      { type: "Paper", weight: 0.8 },
      { type: "Glass", weight: 0.5 },
    ],
  },
  {
    id: "bin34",
    name: "Surulere - National Stadium",
    fill: 85,
    position: [6.5123, 3.3734],
    status: "critical",
    lastCollection: new Date("2025-02-16"),
    ward: "Ward C",
    wasteBreakdown: [
      { type: "Plastic", weight: 4.4 },
      { type: "Mixed", weight: 4.1 },
      { type: "Organic", weight: 3.2 },
      { type: "Paper", weight: 2.1 },
      { type: "Glass", weight: 0.9 },
    ],
  },
  {
    id: "bin37",
    name: "Apapa - Wharf Road",
    fill: 92,
    position: [6.4474, 3.3594],
    status: "critical",
    lastCollection: new Date("2025-01-15"),
    ward: "Ward C",
    wasteBreakdown: [
      { type: "Mixed", weight: 5.2 },
      { type: "Plastic", weight: 4.3 },
      { type: "Paper", weight: 3.5 },
      { type: "Organic", weight: 2.8 },
      { type: "Glass", weight: 1.6 },
    ],
  },
  {
    id: "bin49",
    name: "Satellite Town - Alaba Market",
    fill: 84,
    position: [6.4556, 3.2234],
    status: "critical",
    lastCollection: new Date("2025-02-16"),
    ward: "Ward C",
    wasteBreakdown: [
      { type: "E-waste", weight: 7.6 },
      { type: "Plastic", weight: 4.1 },
      { type: "Mixed", weight: 2.9 },
      { type: "Paper", weight: 1.5 },
      { type: "Glass", weight: 0.7 },
    ],
  },
];

export default bins;
